services:
  npm-db:
    image: 'mariadb:latest'
    container_name: npm-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm_root_pass'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm_password'
    volumes:
      - npm_db_data:/var/lib/mysql
    networks:
      - red_interna

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      DB_MYSQL_HOST: "npm-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm_password"
      DB_MYSQL_NAME: "npm"
    depends_on:
      - npm-db
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - red_interna

  app:
    build: ./app
    container_name: servidor-api-flask
    restart: unless-stopped
    environment:
      - DB_HOST=servidor-bd-ejemplo
      - DB_USER=app_user
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=appdb
    depends_on:
      - servidor-bd-ejemplo
    networks:
      - red_interna
    expose:
      - "5000"

  servidor-bd-ejemplo:
    image: mysql:8.0
    container_name: servidor-bd-ejemplo
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - red_interna     


  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - kuma_data:/app/data
    networks:
      - red_interna
    expose:
      - "3001"
    depends_on:
      - servidor-bd-ejemplo

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - red_interna
    expose:
      - "8080"

networks:
  red_interna:
    driver: bridge

volumes:
  db_data:
  npm_data:
  npm_letsencrypt:
  npm_db_data:
  kuma_data: